<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 7</title>
</head>
<body>
	<h1>Devionoty</h1><br>
	<h3>Урок 31 завдання 7</h3><br>
	 Создать форму с полями username, email, message. Сериализовать данные, полученные при отправке формы и вывести полученную строку на экран.<br>
	<b><?=$message?></b>
	<form method="post">
		<input type="text" name="name" placeholder="Ваше ім'я: "
		value="<?=requestPost('name')?>"><br>
		<input type="email" name="email" placeholder="Email: "
		value="<?=requestPost('email')?>"><br>
		<input type="text" name="phone" placeholder="Ваше повідомлення: "
		value="<?=requestPost('phone')?>"><br>
		<input type="submit" name="submit" value="Надіслати"><br>
		Серіалізовані дані зі змінної $_POST:<br>
		<?=serialize($_POST)?>
	</form>
</body>
</html>