<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 7</title>
</head>
<body>
	<h1>Register</h1><br>
	<b><?=$message?></b>
	<form method="post">
		<input type="text" name="first_name" placeholder="Firs name: "
		value="<?=requestPost('first_name')?>"><br>
		<input type="text" name="last_name" placeholder="Last name: "
		value="<?=requestPost('last_name')?>"><br>
		<input type="email" name="email" placeholder="Email"
		value="<?=requestPost('email')?>"><br>
		<input type="submit" name="submit" value="Надіслати"><br>
	</form>
</body>
</html>