<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 7</title>
</head>
<body>
	<h1>Devionoty</h1><br>
	<h3>Урок 44 завдання 13</h3><br>
	 Создать алгоритм вычисления максимального значения двух заданных переменных.
	<hr>
	<?="Результатом роботи функції maximum(arg1, arg2) при аrg1 = $a, arg2 = $b: $c<br>"?>
	<?="Результатом роботи функції maximum(arg1, arg2) при аrg1 = $d, arg2 = $e: $h<br>"?>
	<?="Результатом роботи функції maximum(arg1, arg2) при аrg1 = $f, arg2 = $g: $i<br>"?>
</body>
</html>