<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 7</title>
</head>
<body>
	<h1>Devionoty</h1><br>
	<h3>Урок 33 завдання 8</h3><br>
	Вычислить количество секунд в году и присвоить это значение переменной. Вычислить остаток от деления этого значения на 2 <br><hr>
	<?="У році {$consts['YEAR']} днів, у дні {$consts['DAY']} годин, у годині {$consts['HOUR']} хвилин, у хвилині {$consts['MINUTE']} секунд.<br>
	Це означає, що у році $yhour годин, або $yminute хвилин, або $ysecond секунд. Остача від ділення $ysecond на 2  = $remainder"?>
</body>
</html>