<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 7</title>
</head>
<body>
	<h1>Devionoty</h1><br>
	<h3>Урок 36 завдання 10</h3><br>
	<ol>
		<li>Вычислить значение выражения: false && true || false && true || !false && true</li>
		<li>Вывести на экран true/false в зависимости о того, делится переменная $x на 2 или нет.</li>
	</ol><hr>

	<?="1. Значення виразу false && true || false && true || !false && true = " . $her . "<br>"?>
	<?="2. 99 не ділится на 2, тому функція div2() повертає: " . $div2?>
</body>
</html>