<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 7</title>
</head>
<body>
	<h1>Devionoty</h1><br>
	<h3>Урок 47 завдання 14</h3><br>
	 Создать алгоритм определения всех простых чисел в промежутке от 1 до 100 при помощи for. Простое число - это число которое делится только на себя и на 1.
	<hr>
	<?="Результатом роботи функції primerange(arg1, arg2) при аrg1 = $a, arg2 = $b:<br>"?>
	<?php print_r($i); echo '<br>'; echo '<br>';?>
	<?="Результатом роботи функції primerange(arg1, arg2) при аrg1 = $f, arg2 = $g:<br>"?>
	<?php print_r($h); echo '<br>'; echo '<br>';?>

</body>
</html>